import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import { NuqsAdapter } from 'nuqs/adapters/next/app'

import { ORPCQueryProvider } from '@/lib/orpc-rq.client'

import { ToasterProvider } from '@/components/toaster-provider'

import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NuqsAdapter>
          <ORPCQueryProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              {children}
              <ToasterProvider />
              <ReactQueryDevtools initialIsOpen={false} />
            </ThemeProvider>
          </ORPCQueryProvider>
        </NuqsAdapter>
      </body>
    </html>
  )
}
